# vi: set ai ts=4 sw=4 : -*-  tab-width:4  c-basic-offset:4   -*-
# vim: set comments= cinoptions=\:0,t0,+8,c4,C1 :
#****************************************************************************
# (C) Copyright 2014-2021 Lynx Software Technologies, Inc. All rights reserved.
# (C) Copyright 2007-2014 LynuxWorks, Inc. All rights reserved.
#****************************************************************************

DRV_NAME = lcs
CERTIFIED = true

DRV_EXTRA_FILES = lcsthreads.x lcsptp.x

include $(ENV_PREFIX)/sys/DRV_RULES

# End of file.
